/// Example: Using multi_index_lru with real sbepp-generated message types
///
/// Build requirements for this example:
/// 1. sbepp installed (providing sbepp::sbepp CMake package)
/// 2. market_cache schema generated by sbeppc into a directory that contains:
///    market_cache/messages/quote.hpp
///
/// Example configure:
/// cmake -S . -B build \
///   -DMULTI_INDEX_LRU_BUILD_SBEPP_EXAMPLE=ON \
///   -DMULTI_INDEX_LRU_SBEPP_GENERATED_DIR=/path/to/generated

#include <multi_index_lru/container.hpp>
#include <multi_index_lru/sbe_cache.hpp>

#include <boost/multi_index/composite_key.hpp>
#include <boost/multi_index/hashed_index.hpp>
#include <boost/multi_index/ordered_index.hpp>

#include <sbepp/sbepp.hpp>
#include <market_cache/messages/quote.hpp>

#include <cstdint>
#include <iostream>
#include <span>
#include <string>
#include <tuple>
#include <vector>

namespace {

using QuoteEntry = multi_index_lru::SbeEntryWithKeys_t<std::uint16_t, std::uint32_t>;

struct TemplateTag {};
struct SecurityTag {};
struct CompositeTag {};

using QuoteCache = multi_index_lru::Container<
    QuoteEntry,
    boost::multi_index::indexed_by<
        boost::multi_index::ordered_unique<
            boost::multi_index::tag<TemplateTag>,
            multi_index_lru::sbe_key<0, QuoteEntry>>,
        boost::multi_index::hashed_unique<
            boost::multi_index::tag<SecurityTag>,
            multi_index_lru::sbe_key<1, QuoteEntry>>,
        boost::multi_index::ordered_unique<
            boost::multi_index::tag<CompositeTag>,
            boost::multi_index::composite_key<
                QuoteEntry,
                multi_index_lru::sbe_key<0, QuoteEntry>,
                multi_index_lru::sbe_key<1, QuoteEntry>>>>>;

std::vector<uint8_t> EncodeQuote(std::uint16_t template_id, std::uint32_t security_id) {
    std::vector<char> buffer(128, 0);

    auto msg = sbepp::make_view<market_cache::messages::quote>(buffer.data(), buffer.size());
    sbepp::fill_message_header(msg);
    msg.template_id(template_id);
    msg.security_id(security_id);

    const auto encoded_size = sbepp::size_bytes(msg);
    return std::vector<uint8_t>(
        reinterpret_cast<const uint8_t*>(buffer.data()),
        reinterpret_cast<const uint8_t*>(buffer.data()) + encoded_size);
}

}  // namespace

int main() {
    auto make_quote_view = [](std::span<const uint8_t> data) {
        return sbepp::make_const_view<market_cache::messages::quote>(
            reinterpret_cast<const char*>(data.data()), data.size());
    };

    auto builder = multi_index_lru::make_sbe_entry_builder<QuoteEntry>(
        make_quote_view,
        multi_index_lru::make_sbe_field<std::uint16_t>(
            [](const auto& quote) { return static_cast<std::uint16_t>(quote.template_id()); }),
        multi_index_lru::make_sbe_field<std::uint32_t>(
            [](const auto& quote) { return static_cast<std::uint32_t>(quote.security_id()); }));

    QuoteCache cache(3);
    cache.emplace(builder.build(EncodeQuote(101, 5'001)));
    cache.emplace(builder.build(EncodeQuote(102, 5'002)));
    cache.emplace(builder.build(EncodeQuote(103, 5'003)));

    auto it = cache.find<SecurityTag>(5'002U);
    if (it == cache.end<SecurityTag>()) {
        std::cerr << "quote not found\n";
        return 1;
    }

    const auto quote_view = it->view(make_quote_view);
    std::cout << "Found quote: template_id=" << static_cast<std::uint16_t>(quote_view.template_id())
              << ", security_id=" << static_cast<std::uint32_t>(quote_view.security_id()) << '\n';

    auto composite = cache.find<CompositeTag>(std::make_tuple<std::uint16_t, std::uint32_t>(103, 5'003));
    if (composite != cache.end<CompositeTag>()) {
        std::cout << "Composite lookup succeeded, payload bytes=" << composite->raw_data().size() << '\n';
    }

    return 0;
}
